"""empty message

Revision ID: 73cf4f64e44e
Revises: 
Create Date: 2023-01-26 11:24:19.539719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cf4f64e44e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=80), nullable=False),
    sa.Column('svg', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=80), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('host_sid', sa.String(), nullable=False),
    sa.Column('player_sid', sa.String(), nullable=True),
    sa.Column('hostURI', sa.String(), nullable=True),
    sa.Column('playerURI', sa.String(), nullable=True),
    sa.Column('hostBool', sa.Boolean(), nullable=True),
    sa.Column('playerBool', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_sid'),
    sa.UniqueConstraint('player_sid'),
    sa.UniqueConstraint('room_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('sid', sa.String(length=120), nullable=True),
    sa.Column('avatarUrl', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('room')
    op.drop_table('canvas')
    # ### end Alembic commands ###
